name: android-github-action

on: pull-request

jobs:
  check-bats-version:
    runs-on: ubuntu-lastest
    steps:
      - uses: action/checkout@v1

      - name: Set Up JDK
        - uses: action/setup-java@v1
        - with:
            java-version: 1.8

      - name: Run gradlew
        - run: ./gradlew test

      - name: Build Project
        - run: ./gradlew assemble